import type PDFKit from "pdfkit";

export type InvoicePdfInput = {
  invoiceNo: string;
  storeName: string;
  customerName: string;
  customerPhone: string;
  date: string;
  products: Array<{ name: string; quantity: number; price: number }>;
  total: number;
};

export async function renderInvoicePdf(input: InvoicePdfInput): Promise<Buffer> {
  const { default: PDFDocument } = await import("pdfkit");
  type PDFDocumentCtor = new (options?: PDFKit.PDFDocumentOptions) => PDFKit.PDFDocument;
  const Doc = PDFDocument as unknown as PDFDocumentCtor;
  const doc = new Doc({ margin: 40, size: "A4" });
  const chunks: Buffer[] = [];
  doc.on("data", (c: Buffer) => chunks.push(c));
  const done = new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });

  doc.fontSize(20).text("Invoice", { align: "left" });
  doc.moveDown(0.5);
  doc.fontSize(10).text(`Invoice ID: ${input.invoiceNo}`);
  doc.text(`Date: ${input.date}`);
  doc.text(`Store: ${input.storeName}`);
  doc.moveDown(0.5);
  doc.text(`Customer: ${input.customerName}`);
  doc.text(`Phone: ${input.customerPhone}`);
  doc.moveDown(1);

  doc.fontSize(11).text("Items", { underline: true });
  doc.moveDown(0.3);
  for (const p of input.products) {
    const lineTotal = p.quantity * p.price;
    doc.fontSize(10).text(`${p.name} x ${p.quantity} @ $${p.price.toFixed(2)} = $${lineTotal.toFixed(2)}`);
  }
  doc.moveDown(1);
  doc.fontSize(12).text(`Total: $${input.total.toFixed(2)}`, { align: "right" });
  doc.moveDown(1.5);
  doc.fontSize(9).fillColor("#555").text("Generated by LAAS24");
  doc.end();

  return done;
}
